### PR TITLE
CI/CL

### PR DESCRIPTION
**Pull request by uyozulku**

### CODE REVIEW

**Comment by wu-rymd** [comment]
@uyozulku 
```
mv ./target/site/jacoco ./reports/jacoco
mv: cannot move './target/site/jacoco' to './reports/jacoco/jacoco': Directory not empty
```

I think `cp` would be better (`cp -R` for copying directories recursively), we can keep the copies in `target/` :D

**Comment by uyozulku** [comment]
> @uyozulku
> 
> ```
> mv ./target/site/jacoco ./reports/jacoco
> mv: cannot move './target/site/jacoco' to './reports/jacoco/jacoco': Directory not empty
> ```
> 
> I think `cp` would be better (`cp -R` for copying directories recursively), we can keep the copies in `target/` :D

I can do that, but since Git ignores the target/ directory does it matter?

**Comment by uyozulku** [comment]
> @uyozulku
> 
> ```
> mv ./target/site/jacoco ./reports/jacoco
> mv: cannot move './target/site/jacoco' to './reports/jacoco/jacoco': Directory not empty
> ```
> 
> I think `cp` would be better (`cp -R` for copying directories recursively), we can keep the copies in `target/` :D



> @uyozulku
> 
> ```
> mv ./target/site/jacoco ./reports/jacoco
> mv: cannot move './target/site/jacoco' to './reports/jacoco/jacoco': Directory not empty
> ```
> 
> I think `cp` would be better (`cp -R` for copying directories recursively), we can keep the copies in `target/` :D

I can do that but since Git will ignore the /target directory, does it matter that we copy over to /reports instead of moving the files?

**Comment by wu-rymd** [comment]
> > I think `cp` would be better (`cp -R` for copying directories recursively), we can keep the copies in `target/` :D
> 
> I can do that but since Git will ignore the /target directory, does it matter that we copy over to /reports instead of moving the files? @wu-rymd

@uyozulku Nope! It doesn't matter in the end, but `mv` will not merge or overwrite directories, giving you the error in your workflow, so since it doesn't matter, I think `cp` or `cp -R` might be a better choice just to overcome it :D 👍

**Pull request closed without merging**
