### PR TITLE
Add Cryptocurrency and NFT models, controllers

### PR DESCRIPTION
**Pull request by uyozulku**
Added models, services, and controllers for Cryptocurrencies and NFTs, as well as a new `ResourceAlreadyExistsException` to throw when a client tries creating a new tradable that already exists in the database

### CODE REVIEW

**Review by jlamborn324 — COMMENTED** [review]
Looks good, can you wait until @wu-rymd's custom exceptions are pulled into main and then implement those in this branch?

**Comment by uyozulku** [comment]
> Looks good, can you wait until @wu-rymd's custom exceptions are pulled into main and then implement those in this branch?

**Comment by uyozulku** [comment]
> Looks good, can you wait until @wu-rymd's custom exceptions are pulled into main and then implement those in this branch?

@jlamborn324 I don't think the new exceptions apply to this PR, but I am adding a `ResourceAlreadyExistsException` for when a client tries adding a stock/crypto/etc. that already exists in the database

**Comment by boraelci** [comment]
I think Joey is saying: switch to 'add_crypto_nft' branch locally, then do 'git merge main' so that you get the latest changes from main. Then, push to this branch again and merge this PR. We also need unit tests for crypto and nfts, but I guess you can do that in a separate PR

**Review by boraelci — APPROVED** [review]

**Pull request merged**
